/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarComponent: typeof import('./src/components/AppBarComponent.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
